name: Release

# This file is very verbose, but things have to be split into separate jobs to
# allow them to run in parallel. There seems to be no way to share the Docker
# build context between jobs, so the Docker set-up has to be copied in each one.

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  clean:
    runs-on: ubuntu-22.04
    steps:
      - name: "Prune docker"
        run: "docker system prune -f --all"

  build-dep-free-images:
    needs: clean
    runs-on: ubuntu-22.04
    steps:
      - name: "Get the code"
        uses: actions/checkout@v3
      - name: "Get tag version"
        run: echo "TL_YEAR_VERSION=$(cat TEXLIVE_YEAR)" >> $GITHUB_ENV
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Log in to DockerHub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build container image"
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          context: .
          tags: csegarragonz/latex-docker:texlive_${{ env.TAG_VERSION }}
